AWSTemplateFormatVersion: "2010-09-09"
Description: "Arjun's Final Test - Deploy ECS Fargate App with CI/CD and Monitoring"

Parameters:
  GitHubOwner:
    Type: String
    Default: "your-github-username"
  GitHubRepo:
    Type: String
    Default: "wildrydes-finaltest"
  GitHubBranch:
    Type: String
    Default: "main"
  GitHubOAuthToken:
    Type: String
    NoEcho: true
  VpcCIDR:
    Type: String
    Default: "10.0.0.0/16"

Resources:

  ArjunVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: arjun-vpc

  ArjunInternetGateway:
    Type: AWS::EC2::InternetGateway

  ArjunVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ArjunVPC
      InternetGatewayId: !Ref ArjunInternetGateway

  ArjunPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ArjunVPC
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: arjun-public-subnet-1

  ArjunPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ArjunVPC
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: arjun-public-subnet-2

  ArjunECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: arjun-app-repo

  ArjunECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: arjun-cluster

  ArjunTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      RoleName: arjun-ecs-execution-role

Outputs:
  VPCId:
    Description: "VPC ID"
    Value: !Ref ArjunVPC

  ECSClusterName:
    Description: "ECS Cluster Name"
    Value: !Ref ArjunECSCluster

  ECRRepositoryUri:
    Description: "ECR Repo URI"
    Value: !Ref ArjunECRRepository

  LoadBalancerDNS:
    Description: "Public DNS of ALB"
    Value: !GetAtt ArjunALB.DNSName
